# Generated by Django 4.0.4 on 2022-07-16 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cycle_index', models.PositiveIntegerField()),
                ('population_size', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_start', models.DateTimeField(auto_now_add=True)),
                ('timestamp_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_horizon', models.PositiveIntegerField()),
                ('r0', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('initialism', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_start', models.DateTimeField(auto_now_add=True)),
                ('timestamp_end', models.DateTimeField(null=True)),
                ('instance_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='simulations.instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='parameters',
            constraint=models.UniqueConstraint(fields=('time_horizon', 'r0'), name='AK_simulation_parameters_unique'),
        ),
        migrations.AddField(
            model_name='instance',
            name='parameters_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='simulations.parameters'),
        ),
        migrations.AddField(
            model_name='data',
            name='population_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='simulations.population'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='simulations.sample'),
        ),
        migrations.AddConstraint(
            model_name='instance',
            constraint=models.CheckConstraint(check=models.Q(('timestamp_start__lte', django.db.models.expressions.F('timestamp_end'))), name='CHK_simulation_instance_timestamp_start_lt_timestamp_end'),
        ),
    ]
