# Generated by Django 4.0.4 on 2022-07-15 06:20

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.postgresql.schema import BaseDatabaseSchemaEditor


def populate_populations(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    # Defines which populations simulations can use
    POPULATIONS = (
        {
            "name": "uninfected",
            "initialism": "U",
            "description": "Nodes that are able to be infected",
        },
        {
            "name": "exposed",
            "initialism": "E",
            "description": "Nodes that have become infected but cannot yet spread infection",
        },
        {
            "name": "infected asymptomatic",
            "initialism": "A",
            "description": "Nodes that have become infected and can spread infection",
        },
        {
            "name": "infected symptomatic",
            "initialism": "S",
            "description": "Nodes that have become infected but cannot spread infection (due to quarantining)",
        },
        {
            "name": "recovered",
            "initialism": "R",
            "description": "Nodes that have recovered from infection and cannot become infected again",
        },
        {
            "name": "dead",
            "initialism": "D",
            "description": "Nodes that have died due to their disease",
        },
    )
    Population = apps.get_model("simulations", "Population")
    for p in POPULATIONS:
        population = Population(
            name=p["name"], initialism=p["initialism"], description=p["description"]
        )
        population.save()


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_populations)]
