# Generated by Django 4.0.4 on 2022-07-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_remove_parameters_ak_simulation_parameters_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cycle_index',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='population_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.population'),
        ),
        migrations.AlterField(
            model_name='data',
            name='population_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.sample'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='parameters_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.parameters'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='r0',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='time_horizon',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulations.instance'),
        ),
    ]
