# Generated by Django 4.0.4 on 2022-07-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_alter_data_cycle_index_alter_data_population_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='population_id',
            new_name='population',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='parameters_id',
            new_name='parameters',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='instance_id',
            new_name='instance',
        ),
    ]
