# Generated by Django 4.0.4 on 2022-07-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_rename_population_id_data_population_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='population',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['id']},
        ),
    ]
