# Generated by Django 4.0.4 on 2022-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_alter_data_options_alter_population_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='population',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='instance',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
