# Generated by Django 4.0.4 on 2022-07-18 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0007_alter_data_options_alter_instance_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parameters',
            name='sample_size',
            field=models.PositiveIntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('time_horizon', 'r0', 'sample_size')},
        ),
    ]
