# Generated by Django 4.0.4 on 2022-07-18 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0008_alter_parameters_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='sample_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
