# Generated by Django 4.0.4 on 2022-07-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simulations', '0010_alter_parameters_r0_alter_parameters_sample_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='graph_id',
            field=models.UUIDField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='instance',
            name='graph_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
