# Generated by Django 4.0.4 on 2022-07-25 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simulations', '0011_instance_graph_id_instance_graph_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='graph_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='graph_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
