# Generated by Django 4.0.4 on 2022-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0012_alter_instance_graph_id_alter_instance_graph_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='graph_id',
            field=models.UUIDField(),
        ),
    ]
