# Generated by Django 4.0.4 on 2022-08-03 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0013_alter_instance_graph_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parameters',
            name='cycles_per_day',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='parameters',
            name='death_probability',
            field=models.DecimalField(decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='exogenous_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='exogenous_frequency',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='initial_infected_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='symptoms_probability',
            field=models.DecimalField(decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='test_cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='test_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='test_results_delay',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='test_sensitivity',
            field=models.DecimalField(decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='test_specificity',
            field=models.DecimalField(decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='time_to_infection_mean',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='time_to_infection_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='time_to_recovery_mean',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parameters',
            name='time_to_recovery_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='r0',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('sample_size', 'initial_infected_count', 'cycles_per_day', 'time_horizon', 'exogenous_amount', 'exogenous_frequency', 'r0', 'time_to_infection_mean', 'time_to_infection_min', 'time_to_recovery_mean', 'time_to_recovery_min', 'symptoms_probability', 'death_probability', 'test_specificity', 'test_sensitivity', 'test_cost', 'test_results_delay', 'test_rate')},
        ),
    ]
