[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"


[tool.black]
target-version = ['py39']


[tool.pytest.ini_options]
addopts = "--cov=abmseir"
testpaths = [
	"tests",
]
