# Generated by Django 4.0.4 on 2022-06-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='circulantgraph',
            table='graphs_circulant',
        ),
        migrations.AlterModelTable(
            name='completegraph',
            table='graphs_complete',
        ),
    ]
