# Generated by Django 4.0.4 on 2022-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_alter_circulantgraph_table_alter_completegraph_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='circulantgraph',
            constraint=models.UniqueConstraint(fields=('order', 'jumps'), name='AK_graph_circulant_properties'),
        ),
        migrations.AddConstraint(
            model_name='completegraph',
            constraint=models.UniqueConstraint(fields=('order',), name='AK_graph_complete_properties'),
        ),
    ]
