# Generated by Django 4.0.4 on 2022-06-02 18:03

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_circulantgraph_ak_graph_circulant_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulantgraph',
            name='jumps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]), size=None),
        ),
    ]
