# Generated by Django 4.0.4 on 2022-06-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_alter_circulantgraph_jumps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circulantgraph',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='completegraph',
            options={'ordering': ['-order']},
        ),
    ]
