# Generated by Django 4.0.4 on 2022-06-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_alter_circulantgraph_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circulantgraph',
            options={'ordering': ['-order', '-jumps']},
        ),
    ]
