# Generated by Django 4.0.4 on 2022-07-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_alter_circulantgraph_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CirculantGraph',
            new_name='Circulant',
        ),
        migrations.RenameModel(
            old_name='CompleteGraph',
            new_name='Complete',
        ),
        migrations.AlterModelTable(
            name='circulant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='complete',
            table=None,
        ),
    ]
